org.gradle.jvmargs=-Xmx10G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=realisticnametag
mod_name=Realistic Nametag
mod_license=All rights reserved.
mod_version=1.3.1
mod_group_id=io.github.hikoma0000
mod_authors=hikoma0000
mod_description=Makes name tag behave realistically, hiding them behind blocks and objects.
mod_logo_file=logo.png
mod_issue_tracker_url=https://github.com/hikoma0000/Realistic-Nametag/issues
mod_credits=
mod_update_json_url=
mod_display_url=https://github.com/hikoma0000/Realistic-Nametag/tree/forge/1.20.1


jei_version=15.2.0.27
cloth_config_version=11.1.136