modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
logoFile="${mod_logo_file}"
issueTrackerURL="${mod_issue_tracker_url}"
credits="${mod_credits}"
updateJSONURL="${mod_update_json_url}"
displayURL="${mod_display_url}"


[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"