modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/hikoma0000/Realistic-Nametag/issues"


[[mixins]]
config = "realisticnametag.mixins.json"


[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
credits = ''''''
logoFile="logo.png"
displayURL="https://github.com/hikoma0000/Realistic-Nametag/tree/neoforge/1.21.1"


[[dependencies."${mod_id}"]]
modId="neoforge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="carryon"
mandatory=false
versionRange="${carryon_version_range}"
ordering="NONE"
side="BOTH"